### ISSUE TITLE
"Unexpected end of file!" when opening a newer binary place

### ISSUE THREAD

**Issue by trussive** [CloneTrooper1019/Roblox-File-Format#3]
I'm currently writing something in C# with this library, however trying to open a binary place file made using the most recent Roblox as of writing (0.474.5.420553) just gives me "Unexpected end of file!"

I'm opening the place file with the FileName string of OpenFileDialog.

Attached is a classic baseplate game with no modifications.

[Baseplate.zip](https://github.com/CloneTrooper1019/Roblox-File-Format/files/6328472/Baseplate.zip)

**Comment by CloneTrooper1019** [comment]
The circumstances of this bug are peculiar and could have only appeared recently.

In short it occurred because I implemented property type 29 as the ProtectedString type, but apparently this type was not canonically present in production builds. It only appeared in the `Client CoreScripts` model they have uploaded to the LuaAppsBot account.

As a result, the new OptionalCFrame property type is using this ID and the ProtectedString reading/writing logic is incorrectly reading the buffer for this property. In any other circumstance the unknown property would have been ignored, and I’ll be more careful not to implement property types if I can’t verify they’re actually used in a production context.

**Comment by CloneTrooper1019** [comment]
Alright hey sorry it took me so long to take care of this. The issue should be resolved.
Turns out Roblox actually corrupted this property called WorldPivotInternal which no longer exists.
I've caught everything up with the latest spec changes and features. Let me know if the latest patch fixes everything!

**Comment by CloneTrooper1019** [comment]
Will be closing this in a few days if I don't hear back.
